version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Helsinki"
    groups:
      all-dependencies:
        patterns:
          - "*"
    rebase-strategy: "auto"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
